# Generated by Django 4.1.4 on 2022-12-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epicbot_interface", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANED", "PLANED"),
                            ("ACTIVE", "ACTIVE"),
                            ("FINISHED", "FINISHED"),
                            ("ERROR", "ERROR"),
                        ],
                        default="PLANED",
                        max_length=10,
                    ),
                ),
                ("logs", models.TextField(blank=True, null=True)),
                ("next_run_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
