# Generated by Django 3.2.20 on 2023-08-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicbot_interface', '0002_joblogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
